"""Added profile fields

Revision ID: 019e84796d5d
Revises: bdf30c8c9f49
Create Date: 2025-10-26 20:14:58.109522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019e84796d5d'
down_revision = 'bdf30c8c9f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('joined_at')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
